name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # This action simplifies the gh-pages deployment
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub-provided token
        publish_dir: ./public  # Specify the directory where your HTML files are located
        destination_branch: gh-pages  # Specify the branch to push to
