name: Build LaTeX PDF

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the workflow to trigger on
 #   paths:
  #    - 'src/**'  # Trigger only if files in the src folder are changed
  
permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      