name: Build LaTeX PDF

on:
  push:
    branches:
      - main # Adjust this to the branch you want the workflow to trigger on
    paths:
      - "src/**" # Trigger if files in the src folder are changed
      - ".github/workflows/latex-pdf.yml"

permissions:
  contents: write # Ensure the GITHUB_TOKEN has write permissions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      # First pass: Generate .aux file and other necessary auxiliary files
      - name: First LaTeX run (to generate aux files)
        uses: dante-ev/latex-action@latest
        with:
          working_directory: src
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      # Run bibtex now that thesis.aux exists
      - name: Run BibTeX
        uses: dante-ev/latex-action@latest
        with:
          working_directory: src
          root_file: thesis.aux
          compiler: bibtex
          args:

      # Second pass: Now that we have the bibliography, rerun pdflatex to include it
      - name: Second LaTeX run
        uses: dante-ev/latex-action@latest
        with:
          working_directory: src
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      # Third pass: Resolve cross-references and ensure the document is finalized
      - name: Third LaTeX run
        uses: dante-ev/latex-action@latest
        with:
          working_directory: src
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      # Move the PDF from src to the docs directory
      - name: Move PDF to root directory
        run: |
          mkdir -p docs
          mv src/thesis.pdf docs/thesis.pdf
  
      - name: Commit PDF
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/thesis.pdf
          git commit -m "Auto-commit updated pdf file"
          git push
