name: Build LaTeX PDF

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the workflow to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up LaTeX environment
      uses: dante-ev/latex-action@v2
      with:
        root_file: src/thesis.tex  # Replace with your LaTeX file name
        output_directory: pdf_output

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: pdf_output/thesis.pdf  # Replace with your actual LaTeX filename