name: Build LaTeX PDF

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the workflow to trigger on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          working_directory: src
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.aux
          compiler: bibtex
          args: 
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape