name: Build LaTeX PDF

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the workflow to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
    - name: Set up LaTeX environment
      uses: dante-ev/latex-action@2023-A
      with:
        root_file: src/thesis.tex  # Replace with your LaTeX file name
        output_directory: pdf
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: compiled-pdf
        path: pdf/thesis.pdf  # Replace with your actual LaTeX filename