name: Build LaTeX PDF

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the workflow to trigger on
 #   paths:
  #    - 'src/**'  # Trigger only if files in the src folder are changed
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      # First pass: Generate .aux file and other necessary auxiliary files
      - name: First LaTeX run (to generate aux files)
        uses: dante-ev/latex-action@latest
        with:
          working_directory: src
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      # Run bibtex now that thesis.aux exists
      - name: Run BibTeX
        uses: dante-ev/latex-action@latest
        with:
          working_directory: src
          root_file: thesis.aux
          compiler: bibtex
          args:

      # Second pass: Now that we have the bibliography, rerun pdflatex to include it
      - name: Second LaTeX run
        uses: dante-ev/latex-action@latest
        with:
          working_directory: src
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      # Third pass: Resolve cross-references and ensure the document is finalized
      - name: Third LaTeX run
        uses: dante-ev/latex-action@latest
        with:
          working_directory: src
          root_file: thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      # Upload the final PDF as an artifact
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: thesis.pdf
          path: src/thesis.pdf

      # Move the PDF from src to the root directory
      - name: Move PDF to root directory
        run: mv src/thesis.pdf ./thesis.pdf

      # Commit the PDF to the repository
      - name: Commit PDF to repository
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add thesis.pdf
          git commit -m "Add generated thesis PDF"
          git push

